default:
  image: node:lts
  cache:
    paths:
      - node_modules/

pages:
  script:
  - export NODE_OPTIONS=--openssl-legacy-provider
  - npm ci
  #- npm test
  - npm run build

  artifacts:
    paths:
    - public

