default:
  image: node:lts
  cache:
    paths:
      - node_modules/

pages:
  script:
    - export NODE_OPTIONS=--openssl-legacy-provider
    # Install brotli
    - apt-get update
    - apt-get install -y brotli
    # Install Dart Sass
    - curl -LJO https://github.com/sass/dart-sass/releases/download/1.64.1/dart-sass-1.64.1-linux-x64.tar.gz
    - tar -xf dart-sass-1.64.1-linux-x64.tar.gz
    - cp -r dart-sass/ /usr/local/bin
    - rm -rf dart-sass*
    - export PATH=/usr/local/bin/dart-sass:$PATH
    #Installing Hugo
    - curl -LJO https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
    - apt-get install -y ./hugo_extended_${HUGO_VERSION}_linux-amd64.deb
       rm hugo_extended_${HUGO_VERSION}_linux-amd64.deb
    #- npm test
    - npm run build

  artifacts:
    paths:
      - public
